In [1]:
import numpy as np

In [5]:
import numpy as np

lista = [1, 2, 3, 4, 5, 6, 7, 8]
array = np.array(lista)

print(lista)
print(array)

[1, 2, 3, 4, 5, 6, 7, 8]
[1 2 3 4 5 6 7 8]


In [7]:
arr_zeros = np.zeros((5,3))
print(matriz_zero)

NameError: name 'matriz_zero' is not defined

In [8]:
arr_zeros = np.zeros((5,3))
print(arr_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
array[0] 

1

In [10]:
array[0]= 9
print(array[0])

9


In [11]:
matriz_zeros= np.zero((5,3))
print (matriz_zeros)

AttributeError: module 'numpy' has no attribute 'zero'

In [12]:
matriz_zeros= np.zeros((5,3))
print (matriz_zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
lista_de_notas = [9.8,6.5,4.5,8.9,9.3]
notas= np.array(lista_de_notas)
print("Máximo", notas.max())
print("Mínimo", notas.min())
print("Desvio Padrão", notas.std())
print("Média", notas.mean())
print("Posição Menor", nota.argin())

Máximo 9.8
Mínimo 4.5
Desvio Padrão 2.001999000998752
Média 7.8


NameError: name 'nota' is not defined

In [14]:
lista_de_notas = [9.8,6.5,4.5,8.9,9.3]
notas= np.array(lista_de_notas)
print("Máximo", notas.max())
print("Mínimo", notas.min())
print("Desvio Padrão", notas.std())
print("Média", notas.mean())
print("Posição Menor", notas.argin())

Máximo 9.8
Mínimo 4.5
Desvio Padrão 2.001999000998752
Média 7.8


AttributeError: 'numpy.ndarray' object has no attribute 'argin'

In [15]:
lista_de_notas = [9.8,6.5,4.5,8.9,9.3]
notas= np.array(lista_de_notas)
print("Máximo", notas.max())
print("Mínimo", notas.min())
print("Desvio Padrão", notas.std())
print("Média", notas.mean())
print("Posição Menor", notas.argmin())

Máximo 9.8
Mínimo 4.5
Desvio Padrão 2.001999000998752
Média 7.8
Posição Menor 2
